/* Veri Giriþleri */
-- doktor tablosu --
/*
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Kenan', 'Demir', 'E', 55000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Sude', 'Kara', 'K', 62000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Fatih', 'Kayar', 'E', 48000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Utku', 'Saçak', 'E', 67000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Ayþe', 'Sel', 'K', 35000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Yusuf', 'Yalýn', 'E', 52000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Semih', 'Kapar', 'E', 58000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Emine', 'Arslan', 'K', 47000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Hatice', 'Kaya', 'K', 70000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Harun', 'Kýlýç', 'E', 45000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Fatma', 'Kopuz', 'K', 56000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Zeynep', 'Tarý', 'K', 39000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Mustafa', 'Aydýn', 'E', 32000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Arda', 'Has', 'E', 61000)
insert into doktor(doktor_Ad, doktor_Soyad, doktor_Cinsiyet, doktor_Maas)
values('Elif', 'Avcý', 'K', 41000)
*/

-- hasta tablosu --
/*
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Efe', 'Çelik', 65428731928, 'E', '05048192735', '1954-05-14')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Gökhan', 'Bilgeç', 83954761238, 'E', '05023985671', '1966-07-28')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Rümeysa', 'Karalar', 21756349857, 'K', '05071649382', '1980-09-03')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Ahmet', 'Erbil', 76589213746, 'E', '05059384712', '1961-03-17')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Burak', 'Uçar', 48593621715, 'E', '05037264851', '1969-12-30')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Aslý', 'Özer', 96315284739, 'K', '05086532147', '2011-02-08')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Özge', 'Nazlý', 51623748957, 'K', '05092476318', '1995-10-07')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Yiðit', 'Yurtsever', 36195487253, 'E', '05081729645', '2005-07-23')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Gizem', 'Tok', 12457896385, 'K', '05039867214', '1988-04-11')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Okan', 'Dinç', 72395614875, 'E', '05058139476', '2002-09-29')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Kerem', 'Yürekli', 81962735434, 'E', '05098264713', '1992-08-25')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Rüya', 'Terzi', 69274381571, 'K', '05072513694', '1967-10-19')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Aykut', 'Yel', 78542316958, 'E', '05069483217', '1958-02-20')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Yeþim', 'Türk', 53214976857, 'K', '05056294781', '2006-05-29')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Cengiz', 'Topal', 49521378625, 'E', '05063971824', '1978-12-15')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Melike', 'Tatlý', 39874512653, 'K', '05074918236', '2012-06-21')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Alper', 'Ulu', 13986527485, 'E', '05018743692', '1952-11-07')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Yaðmur', 'Yýldýz', 92748563125, 'K', '05046398172', '2003-01-31')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Tuðba', 'Uðurlu', 84726319537, 'K', '05034981762', '2001-11-05')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Hatice', 'Öz', 23571468937, 'K', '05037682914', '1986-06-04')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Can', 'Kara', 36587129456, 'E', '05012345678', '2000-03-15')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Selin', 'Kurt', 89563214758, 'K', '05023456789', '2001-09-20')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Eren', 'Demir', 74185296325, 'E', '05034567890', '2007-07-10')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Elif', 'Özdemir', 98567412358, 'K', '05045678981', '2010-12-05')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Onur', 'Dal', 32589674152, 'E', '05056789017', '1998-05-25')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Zeynep', 'Yýlmaz', 65498732145, 'K', '05067890126', '1993-10-30')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Mert', 'Aydýn', 14725836987, 'E', '05078901231', '2003-04-17')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Asya', 'Çýnar', 74125896352, 'K', '05089012340', '1991-11-12')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Emre', 'Erdoðan', 36985214763, 'E', '05090123454', '1997-08-08')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Aylin', 'Koç', 74196385214, 'K', '05001234562', '1996-02-15')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Canan', 'Þahin', 15963248754, 'K', '05011234565', '1994-06-28')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Kaan', 'Yaman', 14785236985, 'E', '05022345672', '1992-09-22')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Büþra', 'Kara', 75315986247, 'K', '05033456781', '1999-03-07')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Þevval', 'Durmaz', 65412398785, 'K', '05044567851', '1990-12-18')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Burhan', 'Doðan', 14789632145, 'E', '05055678906', '2014-08-03')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Kerem', 'As', 64279034625, 'E', '05726561328', '2009-08-03')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Sude', 'Yaþ', 30384312591, 'K', '05798231454', '1985-09-12')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Cüneyt', 'Okçu', 79246503718, 'E', '05792465781', '2010-10-07')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Kadriye', 'Kartal', 64832190567, 'K', '05167983651', '2007-07-17')
insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
values('Ahmet', 'Dere', 79523465791, 'E', '05795461328', '2000-01-13')
*/

-- muayene tablosu --
/*
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(5, 1, 'Rutin kontrol', '2024-01-01 09:10:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(3, 2, 'Rutin kontrol', '2024-01-01 10:15:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(6, 3, 'Tedavi takibi', '2024-01-02 14:00:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(7, 4, 'Rutin kontrol', '2024-01-03 11:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(10, 5, 'Rutin kontrol', '2024-01-04 16:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(1, 6, 'Hasta muayenesi', '2024-01-05 10:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(13, 7, 'Hasta muayenesi', '2024-01-08 19:05:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(2, 8, 'Hasta muayenesi', '2024-01-09 11:10:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(4, 9, 'Tedavi takibi', '2024-01-09 17:55:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(8, 10, 'Hasta muayenesi', '2024-01-10 12:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(15, 11, 'Tedavi takibi', '2024-01-12 09:20:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(9, 12, 'Rutin kontrol', '2024-01-15 18:40:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(6, 13, 'Rutin kontrol', '2024-01-15 19:35:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(11, 3, 'Tedavi takibi', '2024-01-16 14:00:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(11, 14, 'Hasta muayenesi', '2024-01-16 17:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(5, 15, 'Tedavi takibi', '2024-01-17 19:50:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(14, 16, 'Hasta muayenesi', '2024-01-18 11:45:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(1, 17, 'Rutin kontrol', '2024-01-22 15:40:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(7, 9, 'Tedavi takibi', '2024-01-23 09:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(3, 18, 'Hasta muayenesi', '2024-01-23 19:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(10, 19, 'Hasta muayenesi', '2024-01-25 14:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(4, 11, 'Tedavi takibi', '2024-01-26 14:35:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(8, 20, 'Tedavi takibi', '2024-01-29 09:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(6, 15, 'Tedavi takibi', '2024-01-31 11:20:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(14, 21, 'Hasta muayenesi', '2024-02-02 15:45:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(9, 22, 'Hasta muayenesi', '2024-02-05 09:15:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(1, 23, 'Hasta muayenesi', '2024-02-08 18:50:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(6, 20, 'Tedavi takibi', '2024-02-12 15:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(4, 24, 'Hasta muayenesi', '2024-02-17 14:20:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(8, 25, 'Hasta muayenesi', '2024-02-24 19:55:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(13, 1, 'Rutin kontrol', '2024-03-01 10:15:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(9, 2, 'Rutin kontrol', '2024-03-01 13:35:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(1, 4, 'Rutin kontrol', '2024-03-03 11:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(3, 5, 'Rutin kontrol', '2024-03-04 10:20:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(12, 26, 'Hasta muayenesi', '2024-03-09 10:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(15, 12, 'Rutin kontrol', '2024-03-15 14:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(2, 13, 'Rutin kontrol', '2024-03-16 15:45:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(7, 17, 'Rutin kontrol', '2024-03-22 09:40:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(2, 27, 'Hasta muayenesi', '2024-03-27 13:10:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(7, 28, 'Hasta muayenesi', '2024-04-06 17:35:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(5, 29, 'Hasta muayenesi', '2024-04-19 10:15:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(15, 30, 'Hasta muayenesi', '2024-04-22 18:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(11, 31, 'Hasta muayenesi', '2024-04-25 09:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(3, 32, 'Hasta muayenesi', '2024-04-30 19:50:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(8, 1, 'Rutin kontrol', '2024-05-01 14:50:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(14, 2, 'Rutin kontrol', '2024-05-01 19:20:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(5, 4, 'Rutin kontrol', '2024-05-03 16:15:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(1, 5, 'Rutin kontrol', '2024-05-04 09:40:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(8, 33, 'Hasta muayenesi', '2024-05-08 15:45:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(6, 34, 'Hasta muayenesi', '2024-05-13 16:05:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(3, 12, 'Rutin kontrol', '2024-05-15 17:30:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(11, 13, 'Rutin kontrol', '2024-05-16 13:05:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(10, 35, 'Hasta muayenesi', '2024-05-19 09:25:00')
insert into muayene(doktor_ID, hasta_ID, muayene_Tipi, muayene_Tarihi)
values(9, 17, 'Rutin kontrol', '2024-05-22 18:35:00')
*/

-- randevu tablosu --
/*
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(9, 36, 'Hasta muayenesi', '2024-06-04 10:30:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(3, 37, 'Hasta muayenesi', '2024-06-14 14:35:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(12, 38, 'Hasta muayenesi', '2024-06-23 15:15:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(6, 39, 'Hasta muayenesi', '2024-06-29 09:45:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(14, 1, 'Rutin kontrol', '2024-07-01 14:50:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(4, 2, 'Rutin kontrol', '2024-07-01 19:20:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(9, 4, 'Rutin kontrol', '2024-07-03 16:15:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(8, 5, 'Rutin kontrol', '2024-07-04 09:40:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(1, 40, 'Hasta muayenesi', '2024-07-10 16:30:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(7, 12, 'Rutin kontrol', '2024-07-15 17:30:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(1, 13, 'Rutin kontrol', '2024-07-16 13:05:00')
insert into randevu(doktor_ID, hasta_ID, randevu_Tipi, randevu_Tarih)
values(15, 17, 'Rutin kontrol', '2024-07-22 18:35:00')
*/

-- doktorHasta tablosu --
/*
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 4, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 5, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 6, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 13, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 17, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 23, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(1, 40, 'Aile hekimi')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(2, 8, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(2, 13, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(2, 27, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 2, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 5, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 12, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 18, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 32, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(3, 37, 'Aile hekimi')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(4, 2, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(4, 9, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(4, 11, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(4, 24, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(5, 1, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(5, 4, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(5, 15, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(5, 29, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 3, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 13, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 15, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 20, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 34, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(6, 39, 'Aile hekimi')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(7, 4, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(7, 9, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(7, 12, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(7, 17, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(7, 28, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 1, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 5, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 10, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 20, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 25, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(8, 33, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 2, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 4, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 12, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 17, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 22, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(9, 36, 'Aile hekimi')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(10, 5, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(10, 19, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(10, 35, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(11, 3, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(11, 13, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(11, 14, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(11, 31, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(12, 26, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(12, 38, 'Aile hekimi')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(13, 1, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(13, 7, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(14, 1, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(14, 2, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(14, 16, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(14, 21, 'Acil servis')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(15, 11, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(15, 12, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(15, 17, 'Uzman doktor')
insert into doktorHasta(doktor_ID, hasta_ID, iliski_Turu)
values(15, 30, 'Acil servis')
*/

-- ilac tablosu --
/*
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Actifed', 70, '2026-05-15')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Advil', 95, '2025-09-04')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Aerius', 90, '2025-07-18')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Aferin forte', 70, '2026-10-30')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Allegra', 65, '2026-09-27')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Amiksin', 430, '2025-03-02')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Amoklavin', 95, '2026-06-11')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Arveles', 75, '2025-12-22')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Aspirin', 85, '2026-03-14')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Atenolol', 75, '2025-11-16')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Augmentin', 120, '2025-10-24')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Avil', 95, '2025-11-09')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Breo Ellipta', 650, '2026-01-12')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Burun spreyi', 60, '2027-01-12')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Debridat', 140, '2025-07-03')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Dermovate', 95, '2026-02-23')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Diklofenak', 95, '2026-10-10')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Docetaxel', 4500, '2024-12-25')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Duloksetin', 195, '2026-08-18')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Emadine', 115, '2025-05-28')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Empagliflozin', 770, '2025-02-17')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Flixonase', 120, '2025-01-29')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Fluarix', 545, '2025-04-13')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Fluoksetin', 130, '2026-12-28')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Flutikazon', 190, '2025-09-10')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Furacin', 75, '2026-04-05')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Gaviscon', 140, '2026-11-02')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Gefitinib', 24000, '2025-10-22')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Gemcitabine', 790, '2026-07-01')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Hametan', 85, '2025-12-21')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Insulatard', 515, '2025-06-20')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Ýbuprofen', 80, '2025-08-09')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Ýnfluvac', 560, '2025-08-22')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Ýrinotekan', 850, '2025-03-24')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Lansor', 130, '2026-05-05')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Levofloxacin', 220, '2025-12-12')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Lizobakt', 150, '2025-02-28')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Liraglutid', 1400, '2025-05-01')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Lisinopril', 65, '2026-09-21')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Maalox', 140, '2025-11-27')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Madecassol', 210, '2026-09-06')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Maxalt', 420, '2025-07-25')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Metamizol', 80, '2025-10-18')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Metformin', 120, '2026-01-19')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Metokarbamol', 85, '2025-11-03')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Muscoflex', 95, '2025-04-26')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Mucinex', 140, '2026-06-03') 
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Nab-Paklitaksel', 365, '2025-08-19')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Naltrekson', 700, '2026-02-04')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Naproksen', 130, '2025-03-11')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Nexium', 225, '2025-06-10')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Nimesulid', 95, '2026-11-24')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Nurofen', 120, '2026-07-19')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Orlistat', 830, '2025-08-17')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Panto', 95, '2025-01-21')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Pantpas', 125, '2026-03-22')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Parasetamol', 450, '2024-12-30')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Pastil', 65, '2025-10-20')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Pemetrexed', 11000, '2025-04-16')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Pulmicort', 335, '2026-08-21')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Ramipril', 55, '2024-12-12')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Relestat', 120, '2026-05-13')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Relpax', 110, '2025-03-15')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Rennie', 120, '2026-09-01')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Sertralin', 140, '2026-10-17')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Silverdin', 70, '2025-01-09')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Sumatriptan', 130, '2025-02-14')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Talcid', 210, '2025-03-27')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Theraflu', 60, '2026-10-11')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Tizanidin', 80, '2026-12-01')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Vankomisin', 550, '2025-01-24')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Vaxigrip Tetra', 560, '2026-11-09')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Voltaren', 75, '2026-04-30')
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Zyrtec', 95, '2025-08-15')
*/

-- teshis tablosu --
/*
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(1, 4, 25, 'Astým')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(1, 5, 65, 'Depresyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(1, 6, 7, 'Sinüzit')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(1, 17, 18, 'Akciðer kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(1, 23, 5, 'Bahar alerjisi')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(2, 8, 47, 'Öksürük')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(2, 13, 39, 'Hipertansiyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(2, 27, 15, 'Karýn aðrýsý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(3, 2, 48, 'Pankreas kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(3, 5, 19, 'Depresyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(3, 12, 49, 'Obezite')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(3, 18, 23, 'Grip')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(3, 32, 67, 'Migren')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(4, 9, 45, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(4, 11, 70, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(4, 24, 52, 'Yüksek ateþ')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(5, 1, 44, 'Diyabet')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(5, 4, 60, 'Astým')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(5, 15, 17, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(5, 29, 46, 'Kas aðrýsý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(6, 3, 50, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(6, 13, 10, 'Hipertansiyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(6, 15, 57, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(6, 20, 50, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(6, 34, 56, 'Ülser')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(7, 4, 13, 'Astým')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(7, 9, 57, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(7, 17, 59, 'Akciðer kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(7, 28, 51, 'Gastrit')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(8, 1, 31, 'Diyabet')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(8, 10, 66, 'Yanýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(8, 20, 71, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(8, 25, 20, 'Göz alerjisi')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(8, 33, 36, 'Sinüzit')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(9, 2, 34, 'Pankreas kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(9, 12, 54, 'Obezite')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(9, 17, 28, 'Akciðer kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(9, 22, 16, 'Cilt hastalýklarý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(10, 5, 24, 'Depresyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(10, 19, 74, 'Bahar alerjisi')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(10, 35, 53, 'Baþ aðrýsý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(11, 3, 57, 'Kýrýk')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(11, 13, 61, 'Hipertansiyon')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(11, 14, 33, 'Grip')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(11, 31, 42, 'Migren')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(12, 26, 27, 'Reflü')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(13, 1, 21, 'Diyabet')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(13, 7, 8, 'Kas aðrýsý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(14, 2, 29, 'Pankreas kanseri')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(14, 16, 4, 'Soðuk algýnlýðý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(14, 21, 62, 'Göz alerjisi')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(15, 11, 68, 'Karýn aðrýsý')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(15, 12, 38, 'Obezite')
insert into teshis(doktor_ID, hasta_ID, ilac_ID, teshis_Ad)
values(15, 30, 1, 'Öksürük')
*/

-- recete tablosu --
/*
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(1, 4, '2024-03-03')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(1, 5, '2024-05-04')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(1, 6, '2024-01-05')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(1, 17, '2024-01-22')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(1, 23, '2024-02-08')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(2, 8, '2024-01-09')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(2, 13, '2024-03-16')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(2, 27, '2024-03-27')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(3, 2, '2024-01-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(3, 5, '2024-03-04')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(3, 12, '2024-05-15')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(3, 18, '2024-01-23')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(3, 32, '2024-04-30')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(4, 9, '2024-01-09')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(4, 11, '2024-01-26')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(4, 24, '2024-02-17')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(5, 1, '2024-01-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(5, 4, '2024-05-03')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(5, 15, '2024-01-17')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(5, 29, '2024-04-19')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(6, 3, '2024-01-02')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(6, 13, '2024-01-15')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(6, 15, '2024-01-31')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(6, 20, '2024-02-12')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(6, 34, '2024-05-13')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(7, 4, '2024-01-03')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(7, 9, '2024-01-23')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(7, 17, '2024-03-22')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(7, 28, '2024-04-06')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(8, 1, '2024-05-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(8, 10, '2024-01-10')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(8, 20, '2024-01-29')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(8, 25, '2024-02-24')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(8, 33, '2024-05-08')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(9, 2, '2024-03-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(9, 12, '2024-01-15')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(9, 17, '2024-05-22')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(9, 22, '2024-02-05')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(10, 5, '2024-01-04')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(10, 19, '2024-01-25')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(10, 35, '2024-05-19')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(11, 3, '2024-01-16')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(11, 13, '2024-05-16')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(11, 14, '2024-01-16')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(11, 31, '2024-04-25')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(12, 26, '2024-03-09')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(13, 1, '2024-03-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(13, 7, '2024-01-08')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(14, 2, '2024-05-01')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(14, 16, '2024-01-18')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(14, 21, '2024-02-02')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(15, 11, '2024-01-12')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(15, 12, '2024-03-15')
insert into recete(doktor_ID, hasta_ID, recete_Tarih)
values(15, 30, '2024-04-22')
*/

-- ilacRecete tablosu --
/*
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(25, 1, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(65, 2, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(7, 3, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(18, 4, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(5, 5, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(47, 6, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(39, 7, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(15, 8, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(48, 9, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(19, 10, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(49, 11, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(23, 12, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(67, 13, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(45, 14, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(70, 15, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(52, 16, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(44, 17, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(60, 18, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(17, 19, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(46, 20, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(50, 21, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(10, 22, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(57, 23, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(50, 24, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(56, 25, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(13, 26, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(57, 27, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(59, 28, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(51, 29, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(31, 30, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(66, 31, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(71, 32, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(20, 33, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(36, 34, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(34, 35, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(54, 36, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(28, 37, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(16, 38, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(24, 39, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(74, 40, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(53, 41, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(57, 42, 2)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(61, 43, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(33, 44, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(42, 45, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(27, 46, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(21, 47, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(8, 48, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(29, 49, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(4, 50, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(62, 51, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(68, 52, 1)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(38, 53, 3)
insert into ilacRecete(ilac_ID, recete_ID, adet)
values(1, 54, 1)
*/

-- odeme tablosu --
/*
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(1, 'Nakit', 360, '2024-01-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(1, 'Kredi kartý', 2310, '2024-03-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(1, 'Kredi kartý', 1545, '2024-05-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(2, 'Kredi kartý', 1095, '2024-01-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(2, 'Kredi kartý', 2550, '2024-03-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(2, 'Kredi kartý', 2370, '2024-05-01')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(3, 'Nakit', 260, '2024-01-02')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(3, 'Kredi kartý', 900, '2024-01-16')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(4, 'Kredi kartý', 1950, '2024-01-03')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(4, 'Nakit', 570, '2024-03-03')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(4, 'Kredi kartý', 1005, '2024-05-03')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(5, 'Nakit', 390, '2024-01-04')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(5, 'Nakit', 585, '2024-03-04')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(5, 'Nakit', 420, '2024-05-04')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(6, 'Nakit', 95, '2024-01-05')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(7, 'Nakit', 75, '2024-01-08')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(8, 'Nakit', 140, '2024-01-09')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(9, 'Nakit', 170, '2024-01-09')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(9, 'Kredi kartý', 900, '2024-01-23')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(10, 'Nakit', 70, '2024-01-10')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(11, 'Nakit', 210, '2024-01-12')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(11, 'Nakit', 160, '2024-01-26')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(12, 'Kredi kartý', 2490, '2024-01-15')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(12, 'Kredi kartý', 4200, '2024-03-15')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(12, 'Kredi kartý', 2100, '2024-05-15')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(13, 'Nakit', 225, '2024-01-15')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(13, 'Nakit', 195, '2024-03-16')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(13, 'Nakit', 165, '2024-05-16')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(14, 'Nakit', 560, '2024-01-16')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(15, 'Nakit', 190, '2024-01-17')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(15, 'Kredi kartý', 900, '2024-01-31')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(16, 'Nakit', 70, '2024-01-18')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(17, 'Kredi kartý', 13500, '2024-01-22')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(17, 'Kredi kartý', 33000, '2024-03-22')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(17, 'Kredi kartý', 72000, '2024-05-22')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(18, 'Nakit', 545, '2024-01-23')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(19, 'Nakit', 95, '2024-01-25')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(20, 'Kredi kartý', 1100, '2024-01-29')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(20, 'Nakit', 260, '2024-02-12')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(21, 'Nakit', 120, '2024-02-02')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(22, 'Nakit', 95, '2024-02-05')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(23, 'Nakit', 65, '2024-02-08')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(24, 'Nakit', 95, '2024-02-17')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(25, 'Nakit', 115, '2024-02-24')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(26, 'Nakit', 140, '2024-03-09')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(27, 'Nakit', 140, '2024-03-27')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(28, 'Nakit', 225, '2024-04-06')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(29, 'Nakit', 95, '2024-04-19')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(30, 'Nakit', 70, '2024-04-22')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(31, 'Nakit', 420, '2024-04-25')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(32, 'Nakit', 130, '2024-04-30')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(33, 'Nakit', 220, '2024-05-08')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(34, 'Nakit', 125, '2024-05-13')
insert into odeme(hasta_ID, odeme_Tip, odeme_Tutar, odeme_Tarih)
values(35, 'Nakit', 120, '2024-05-19')
*/

/* Stored Procedure */
-- ID deðeri girilen doktordan randevusu olan hastalarý gösterir
/*
create procedure DoktorunRandevuHastalari 
@DoktorID int
as
begin
	select hasta.hasta_Ad, hasta.hasta_Soyad, hasta.hasta_Cinsiyet, randevu.randevu_Tipi, randevu_Tarih
		from hasta
			inner join randevu on hasta.hasta_ID = randevu.hasta_ID
		where randevu.doktor_ID = @DoktorID
		order by randevu.randevu_Tarih
end
*/
exec DoktorunRandevuHastalari '15'

--Girilen baþlangýç ve bitiþ tarihi arasýndaki muayene bilgilerini gösterir  --
/*
create procedure MuayeneDetay
@BaslangicTarih smalldatetime,
@BitisTarih smalldatetime
as
begin
	select doktor.doktor_Ad, doktor.doktor_Soyad, hasta.hasta_Ad, hasta.hasta_Soyad, muayene.muayene_Tipi, teshis.teshis_Ad, ilac.ilac_Ad, muayene.muayene_Tarihi
		from muayene
			inner join doktor on muayene.doktor_ID = doktor.doktor_ID
			inner join hasta on muayene.hasta_ID = hasta.hasta_ID
			left join teshis on muayene.doktor_ID = teshis.doktor_ID and muayene.hasta_ID = teshis.hasta_ID
			left join ilac on teshis.ilac_ID = ilac.ilac_ID
		where muayene.muayene_Tarihi between @BaslangicTarih and @BitisTarih
end
*/
exec MuayeneDetay '2024-01-01',  '2024-05-22'

-- Yeni hasta ekleme --
/*
create procedure YeniHastaEkle
    @Ad nvarchar(50),
    @Soyad nvarchar(50),
    @TC char(11),
    @Cinsiyet char(1),
    @TelefonNumarasi char(11),
    @DogumTarihi date
as
begin
    if len(@TC) != 11
		begin
			print 'TC kimlik numarasý 11 karakter uzunluðunda olmalýdýr.'
			return
		end
    if len(@TelefonNumarasi) != 11
		begin
			print 'Telefon numarasý 11 karakter uzunluðunda olmalýdýr.'
			return
		end
    if exists (select 1 from hasta where hasta_TC = @TC)
		begin
			print 'Bu kimlik numarasý ile kayýtlý bir hasta bulunmaktadýr.'
			return
		end
    if exists (select 1 from hasta where hasta_Tel = @TelefonNumarasi)
		begin
			print 'Bu telefon numarasý ile kayýtlý bir hasta bulunmaktadýr.'
			return
		end
	if @DogumTarihi > getdate()
    begin
        print 'Doðum tarihi gelecekte olamaz.'
        return
    end
    insert into hasta (hasta_Ad, hasta_Soyad, hasta_TC, hasta_Cinsiyet, hasta_Tel, dogum_Tarih)
	values (@Ad, @Soyad, @TC, @Cinsiyet, @TelefonNumarasi, @DogumTarihi)
		print 'Yeni hasta baþarýyla eklendi.'
end
*/
exec YeniHastaEkle 'Eren', 'Katý', 19849265791, 'E', '05345368219', '1999-02-14'

-- Doktor güncelleme --
/*
create procedure GuncelleDoktor
    @DoktorID int,
	@YeniAd nvarchar(50),
    @YeniSoyad nvarchar(50),
    @YeniCinsiyet char(1),
    @YeniMaas int
as
begin
    -- Doktorun var olup olmadýðýný kontrol et yoksa printi yazdýr
    if not exists (select * from doktor where doktor_ID = @DoktorID)
		begin
			print 'Belirtilen DoktorID ile kayýtlý bir doktor bulunmamaktadýr.'
			return
		end
    update doktor
    set doktor_Ad = @YeniAd,
        doktor_Soyad = @YeniSoyad,
        doktor_Cinsiyet = @YeniCinsiyet,
        doktor_Maas = @YeniMaas
    where doktor_ID = @DoktorID;

    print 'Doktor bilgileri baþarýyla güncellendi.';
end
*/
exec GuncelleDoktor 3, 'Eda', 'Demirci', 'K', 50000

/* Table valued function */
--  Adý girilen doktorun yazdýðý reçeteler, bu reçeteyle ilþkili olan hastalar ve aldýklarý ilaçlarý gösterir --
/*
create function DoktorunReceteler (@DoktarAd nvarchar(50), @DoktorSoyad nvarchar(50))
returns table
as
return
select hasta.hasta_Ad, hasta.hasta_Soyad, recete.recete_ID, ilac.ilac_Ad, ilacRecete.adet, recete.recete_Tarih
	from recete
		inner join doktor on recete.doktor_ID = doktor.doktor_ID
		inner join hasta on recete.hasta_ID = hasta.hasta_ID
		inner join ilacRecete on recete.recete_ID = ilacRecete.recete_ID
		inner join ilac on ilacRecete.ilac_ID = ilac.ilac_ID
	where doktor.doktor_Ad = @DoktarAd and doktor.doktor_Soyad = @DoktorSoyad
*/
select * from DoktorunReceteler ('Harun', 'Kýlýç')

/* Scaler valued function */
-- Hastalarýn yaþýný hesaplama --
/*
create function HastaYasHesapla (@HastaID int)
returns int
as
begin
    declare @Yas int
    declare @DogumTarih date = (select hasta.dogum_Tarih from hasta where hasta.hasta_ID = @HastaID)
	declare @MevcutTarih date = getdate()

	set @Yas = year(@MevcutTarih) - year(@DogumTarih)

	if (month(@MevcutTarih) < MONTH(@DogumTarih) or month(@MevcutTarih) = MONTH(@DogumTarih) and day(@MevcutTarih) < day(@DogumTarih))
	set @Yas = @Yas - 1
    return @Yas
end
*/
select dbo.HastaYasHesapla (5) as Yas

/* Trigger */
-- Ilac tablosuna yeni bir ilaç eklenirken veya mevcut bir ilacýn bilgileri güncellenirken çalýþacak ve son kullanma tarihi geçen ilaçlarý silecek --
/*
create trigger IlacSKTKontrol
on ilac
after insert, update
as
begin
    declare @TarihiGecmisIlacID int;
    declare @TarihiGecmisIlacAdý nvarchar(50);
    -- Tarihi geçmiþ ilaçlarýn ID deðerlerini ve adlarýný bu deðiþkenlere atýyor
    select @TarihiGecmisIlacID = ilac_ID, @TarihiGecmisIlacAdý = ilac_Ad
		from inserted -- insert iþlemi sýrasýnda eklenen satýrlarýn olduðu tablo
	where getdate() > ilac_SKT;
	-- Tarihi geçmiþ ilaç varsa
		if @TarihiGecmisIlacID IS NOT NULL
			begin
				delete from ilac
				where ilac_ID = @TarihiGecmisIlacID;
				print 'Son kullanma tarihi geçmiþ ilaç silindi: ' + @TarihiGecmisIlacAdý;
			end
		else 
			begin
				print 'Son kullanma tarihi geçmiþ bir ilaç bulunmamaktadýr.';
			end
end
*/
insert into ilac(ilac_Ad, ilac_Fiyat, ilac_SKT)
values('Parol', 40, '2024-05-22')

/* Views */
-- HastaMuayeneBilgi --
select * from HastaneMuayeneBilgi

-- HastaRandevuBilgi --
select * from HastaneRandevuBilgi

-- Bir ilacýn kaç reçetede yer aldýðýný gösterir --
select ilac.ilac_Ad,
       (select count(*)
        from ilacRecete
        inner join recete on ilacRecete.recete_ID = recete.recete_ID
        where ilacRecete.ilac_ID = ilac.ilac_ID) as [Bulunduðu Reçete Sayýsý]
from ilac
order by [Bulunduðu Reçete Sayýsý] desc

-- Like yapsý --
select *
from hasta
where hasta_TC like '1%'

select *
from hasta
where hasta_Tel like '%1%'

select *
from hasta
where hasta_TC like '%5'

-- Ortalama doktor maaþý --
select avg(doktor.doktor_Maas) as [Ortalama Doktor Maaþý] 
from doktor

-- ID deðeri girilen ilacý alan hastalarý gösterir --
select hasta.hasta_Ad, hasta.hasta_Soyad, ilac.ilac_Ad, teshis.teshis_Ad, ilac.ilac_SKT
from hasta
inner join teshis on hasta.hasta_ID = teshis.hasta_ID
inner join ilac on teshis.ilac_ID = ilac.ilac_ID
where ilac.ilac_ID ='54'
